# Generated by Django 4.2.7 on 2025-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
