# Generated by Django 4.2.7 on 2025-07-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_employee_adresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="solde_conge_annuel",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="face_encoding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
