# Generated by Django 4.2.7 on 2025-06-18 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("heure_entree", models.TimeField(blank=True, null=True)),
                ("heure_sortie", models.TimeField(blank=True, null=True)),
                ("temps_travaille", models.DurationField(blank=True, null=True)),
                ("retard", models.DurationField(blank=True, null=True)),
                ("heures_supplementaires", models.DurationField(blank=True, null=True)),
                (
                    "methode_entree",
                    models.CharField(
                        choices=[("facial", "Reconnaissance faciale")],
                        default="facial",
                        max_length=20,
                    ),
                ),
                (
                    "methode_sortie",
                    models.CharField(
                        choices=[("facial", "Reconnaissance faciale")],
                        default="facial",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("retard", "En retard"),
                            ("conge", "En congé"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-heure_entree"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
