# Generated by Django 4.2.7 on 2025-07-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_employee_solde_conge_annuel_and_more"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_department",
                to="employees.employee",
            ),
        ),
    ]
