# Generated by Django 4.2.7 on 2025-06-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0003_authentication_groups_authentication_is_staff_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="authentication",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("manager", "Chef de département"),
                    ("employee", "Employé"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
