# Generated by Django 4.2.7 on 2025-07-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_authentication_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authentication",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("manager", "Chef de département"),
                    ("rh", "RH"),
                    ("employee", "Employé"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
