# Generated by Django 4.2.7 on 2025-06-18 09:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_conge",
                    models.CharField(
                        choices=[
                            ("annuel", "Congé annuel"),
                            ("maladie", "Congé maladie"),
                            ("maternite", "Congé maternité"),
                            ("paternite", "Congé paternité"),
                            ("sans_solde", "Congé sans solde"),
                            ("exceptionnel", "Congé exceptionnel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motif", models.TextField()),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "duree_jours",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status_conge",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("rejete", "Rejeté"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "document_justificatif",
                    models.FileField(
                        blank=True, null=True, upload_to="leave_documents/"
                    ),
                ),
                ("commentaire_admin", models.TextField(blank=True, null=True)),
                ("date_approbation", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approuve_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leaves",
                        to="employees.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Congé",
                "verbose_name_plural": "Congés",
                "db_table": "leave",
                "ordering": ["-created_at"],
            },
        ),
    ]
