# Generated by Django 4.2.7 on 2025-07-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="assurance_entreprise",
            field=models.BooleanField(
                default=False, verbose_name="Assurance entreprise"
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="type_justificatif",
            field=models.CharField(
                blank=True,
                choices=[
                    ("certificat", "Certificat médical"),
                    ("carnet", "Carnet de santé"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
