# Generated by Django 4.2.7 on 2025-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leaves", "0002_leave_assurance_entreprise_leave_type_justificatif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="status_conge",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("valide_manager", "Validé par le manager"),
                    ("valide", "Validé par le RH"),
                    ("rejete", "Rejeté"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
    ]
